### ISSUE TITLE
Option to hide resources

### ISSUE THREAD

**Issue by R-Jimenez** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#41] opened 2020-12-28 15:05 UTC
Obligatory "first off, love this" comment. My players were sorely missing the front-page action list from Beyond, and this is a smooth rendition of their design.

One thing I noticed is that with item uses built into feats and tooltips working off them and not the native actor resources, none of my players have any resources, nor do I think they ever will. To that end, one of the only improvements I can see for our use case would be to reclaim that space for the main lists (which grow larger by the day, curse you preparation spellcasters). Even as a blanket option in the module settings it would be very appreciated to be able to just apply a `display: none` rule to the attributes list, or more programmatically just check to see if any/all resources have `max: null`.

Cheers!

**Comment by akrigline** [comment] 2020-12-28 15:08
Hey! Thanks for the feedback, this is a duplicate of #34.

There's another module called [5e Sheet Resources Plus](https://github.com/ardittristan/5eSheet-resourcesPlus) you can use to set the sheet's resources to "0". Since this apparently works and is a pretty elegant solution IMO I'm not terribly interested in doing something on the sheet side.

**Closed** 2020-12-28 15:13 UTC
Labels: duplicate, wontfix
